name: CI - Build

on:
  fork

env:
  DOTNET_VERSION: '10.0.x'
  BUILD_CONFIGURATION: 'Release'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Mensaje Inicial
        run: echo "Iniciando workflow de CI"

      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Verificar Version .NET
        run: dotnet --version

      - name: Build del proyecto 
        run: dotnet build src/Api/Api.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
        continue-on-error: true

      - name: Notifica on build failure
        if: failure()
        run: echo "🥺 La compilacion falla."

      - name: Mensaje Final
        run: echo "Workflow completado exitosamente"